spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessActivity
      database: fitnessActivity


server:
  port: 8082


  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/


